repos:
  - repo: builtin
    hooks:
      - id: check-added-large-files
        args:
          - --maxkb=1024
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-github-workflows
      - id: check-renovate
  - repo: local
    hooks:
      - id: actionlint
        name: Lint GitHub Actions workflows
        entry: mise exec -- actionlint
        files: ^\.github/workflows/.*\.yaml$
        language: system
      - id: prettier
        name: Check formatting
        entry: mise exec -- prettier --check
        files: \.(json|md|yaml)$
        language: system
